### PR TITLE
Add travis build badge

### PR DESCRIPTION
**Pull request by shrmrf**
Added the following build badge:

[Build Status](https://travis-ci.org/thiagoralves/OpenPLC_v3)

This should also trigger a build which we shouldn't cancel :wink:

### CODE REVIEW

**Comment by shrmrf** [comment]
Our goal is to keep this badge green :+1:

**Comment by thiagoralves** [comment]
The last build was cancelled probably because I submitted two commits very close to each other. It looks like two builds were triggered by each commit and they cancelled each other, maybe? I haven't manually cancelled them.

**Comment by shrmrf** [comment]
It's greeeeeeen :finnadie:

**Comment by thiagoralves** [comment]
=)

**Pull request merged**
