### PR TITLE
Change GPIO driver from wiringPi to pigpio

### PR DESCRIPTION
**Pull request by Eduardo-bat**
Changed install and driver files to use pigpio instead of wiringPi on the current Raspberry Pi hardware layer.

### CODE REVIEW

**Comment by LeSpocky** [comment]
> Changed install and driver files to use pigpio instead of wiringPi on the current Raspberry Pi hardware layer.

Neither the pull request nor the commit message answers the question: Why? :thinking:

**Comment by jancumps** [comment]
> Neither the pull request nor the commit message answers the question: Why? 🤔
There's no supported fork of wiringPi anymore.

**Comment by thiagoralves** [comment]
WiringPi is dead since 2019: https://web.archive.org/web/20210126203355/http://wiringpi.com/wiringpi-deprecated/
The community tried to keep it alive but it is a dead-end job. Time to move on. Pigpio is the officially recommended library from Raspberry Pi to deal with GPIO pins in C.

**Comment by LeSpocky** [comment]
Okay get it. Thanks for the explanation. 🙂

However: Why not standard libgpiod from the Linux kernel project like everybody else in the embedded world uses? Does Raspberry Pi have special needs which libgpiod can not cover? 🤔

**Comment by thiagoralves** [comment]
Ease of use, speed, PWM, etc...

**Pull request merged**
