### PR TITLE
Fix install script

### PR DESCRIPTION
**Pull request by shrmrf**
@thiagoralves In this PR, I have tried to resolve the install script (considerably deleted code) via functions.

I tested the script on Debian inside a Virtualbox, and in Docker. Since, I do not need the redundant `RUN` statements in the `Dockerfile` any longer, I have removed those as well.

### CODE REVIEW

**Comment by shrmrf** [comment]
@thiagoralves woops... sorry, let me check

**Comment by shrmrf** [comment]
@thiagoralves should be okay now, maybe squashing the last two commits would be a nice idea :)

**Comment by thiagoralves** [comment]
I read the file again and there is one more thing missing - the section to disable UniPi services on the neuron platform:
echo "[DISABLING UNIPI SERVICES]"
    sudo systemctl stop neuronhost.service
    sudo systemctl disable neuronhost.service
    sudo systemctl stop neurontcp.service
    sudo systemctl disable neurontcp.service
    sudo systemctl stop evok.service
    sudo systemctl disable evok.service

**Comment by shrmrf** [comment]
@thiagoralves thanks again for the review... do you think it's safe to add these lines here: https://github.com/shrmrf/OpenPLC_v3/blob/fix-install-script/install.sh#L273 ?? i.e. right after the platform check (right before `linux_install_deps sudo` line?

**Comment by thiagoralves** [comment]
Yes, it seems to be correct now =)

**Pull request merged**
