### PR TITLE
Templating 

### PR DESCRIPTION
**Pull request by pedromorgan**
## DONT MERGE yet ##

This is just a WIP (hence debug messages etc) and finding my way around; and also for @thiagoralves  to see whats happening and comment.

The `/dashboard` and `/programs` are now in templates, and hacking the rest over next few days

### CODE REVIEW

**Comment by thiagoralves** [comment]
That's great Pete! Thanks. Just keep in mind that I fixed a bunch of stuff today, some of those were related to the webserver code as well. I don't think your changes were related to what I fixed, but please take a look so that you can incorporate those fixes on your branch as well. Thanks!

**Comment by thiagoralves** [comment]
I'm not. You see, I'm much more inclined to low-level programming (PLC
runtime) than web development. This seems nice. Do you want to integrate
use bootstrap with OpenPLC web interface? Just keep in mind that all files
(css and js libs) must be statically allocated (instead of loading from the
internet) because I want the user to be able to use OpenPLC runtime on a
device that is not connected to the internet

**Comment by pedromorgan** [comment]
@thiagoralves yes bootstrap, there should be hardly an difference in appereance, but will work on mobile/tablet etc better

**Comment by pedromorgan** [comment]
@thiagoralves this is good stuff u done, and this is not intended negative...

- u didnt have a webhacker nearby.
- so I give u 20/10 for hacking the website without templates..
- If u were here, I'd kiss u on nose and  buy you a big beer..
- Your not, so I touched the mirror and drunka beer on your behalf ;-)

so I cut it up with tempating, and make it more "standard",
to a webhacker.. this is pretty forward contruct.. kinda..

the interesting part is the compile stuff and interaction with realtime..
hence #6

**Comment by thiagoralves** [comment]
Dude, honestly, I can't keep up with you. You're awesome, really! So, as you noticed, I'm a C++ guy and don't know half of the things you're doing to improve the frontend. What do you use for chatting? IRC? Whatsapp? Messenger? Anything? It would be great if we could schedule a chat someday so that we can share our ideas and I can understand better what is in your mind and what you have done so far. Just let me know! Thanks.

**Comment by pedromorgan** [comment]
@thiagoralves Probably easier to user gitter.im
am here
https://gitter.im/pedromorgan/Lobby

**Comment by pedromorgan** [comment]
slosed with new PR https://github.com/thiagoralves/OpenPLC_v3/pull/79

**Pull request closed without merging**
