### PR TITLE
PR-674 Restructure files so that user-modified files are separate from the rest of the application

### PR DESCRIPTION
**Pull request by garretfick**
Co-authored-by: Karan Mamaniya <kmananiya@smartergridsolutions.com>

### CODE REVIEW

**Comment by pedromorgan** [comment]
Halleluiah... at long last... (this makes pr5 redundant as its largely the same)

**Comment by pedromorgan** [comment]
After this is committed, I'll patch up the refactored webserver code as its was a chicken and egg situation ;-))

**Comment by garretfick** [comment]
@pedromorgan Yes it is redundant. However, this has been well tested and I'm confident in the code.

For the refactored webserver, I suggest having a look at https://github.com/thiagoralves/OpenPLC_v3/issues/66

My proposal there is that your refactored web server should go into a separate repo but define clearly how the parts interact. Also happy to chat on Gitter to fill you in with what I've got planned for some interns I'm trying to hire.

**Comment by garretfick** [comment]
@pedromorgan I might also suggest that you wait one more day before making changes. I'll have another big commit coming shortly.

**Comment by pedromorgan** [comment]
The refactor implements templates and other minor changes.. https://github.com/thiagoralves/OpenPLC_v3/pull/4 so its not that significant ..

**Comment by garretfick** [comment]
There are other changes that we didn't take from your refactor - including making paths an argument. I would be nice to add that here, so I wouldn't delete your branch entirely. There is still good stuff there.

**Pull request merged**
