### PR TITLE
Install and build stuff -new aprroach - WIP

### PR DESCRIPTION
**Pull request by pedromorgan**
Don't merge yet

This is a refactor of the install, setup etc.. snags..

Main snag is that there are files versioned, which should not be.. also the webserv/ dir is contaminated with cpp files, openplc_* files et all

So this aims to cleam up by creating a "build/" dir which is .ignored,
and all stuff into there

- files such as st_optimizer, iec2c are

### CODE REVIEW

**Comment by pedromorgan** [comment]
so following "binaries" in `build/`
- glue_generator
- iec2c
- st_optimizer

**Comment by pedromorgan** [comment]
Major restruct, feedback required @thiagoralves 

# etc/
This is to be considered the "defaults" dir, and as such
the core/hardware, lib , detaults are moved here

# scripts/
shell scripts are moved to a top level dir..

# build/
The build is where all the binary stuff is possible and where exe's are 
this is the local recent build..

# work_dir
The work_dir is a directory where "presistant stuff" such as db/config/uploades etc and need to be outside "openplc" project files..

this is a required config option/argument
stashes stiuff like platform, hardware, sctive program etc.. (later in json/csv)

**Comment by pedromorgan** [comment]
@thiagoralves am refactoring the build/ so its outside
and atmo it compiles tools into /build/st_optmizer etc..

there;s also a `build/src_gen` dir where c files are generates into
```
ls -1 build/src_gen/
Config0.c
Config0.h
Config0.o
custom_layer.h
dnp3.cfg
dnp3.cpp
glueVars.cpp
hardware_layer.cpp
interactive_server.cpp
ladder.h
LOCATED_VARIABLES.h
modbus.cpp
modbus_master.cpp
POUS.c
POUS.h
Res0.c
Res0.o
server.cpp
VARIABLES.csv
```

So in the refactoring.. I dont know whats missing.. ;-(.
```
mkdir: cannot create directory ‘/home/plc/OpenPLC_v3/build/src_gen’: File exists
Optimizing ST program...
Generating C files...
POUS.c
POUS.h
LOCATED_VARIABLES.h
VARIABLES.csv
Config0.c
Config0.h
Res0.c
+ cp /home/plc/OpenPLC_v3/etc/core/ladder.h /home/plc/OpenPLC_v3/build/src_gen
+ cp /home/plc/OpenPLC_v3/etc/core/custom_layer.h /home/plc/OpenPLC_v3/build/src_gen
+ cp /home/plc/OpenPLC_v3/etc/core/dnp3.cpp /home/plc/OpenPLC_v3/build/src_gen
+ cp /home/plc/OpenPLC_v3/etc/core/dnp3.cfg /home/plc/OpenPLC_v3/build/src_gen
+ cp /home/plc/OpenPLC_v3/etc/core/modbus.cpp /home/plc/OpenPLC_v3/build/src_gen
+ cp /home/plc/OpenPLC_v3/etc/core/modbus_master.cpp /home/plc/OpenPLC_v3/build/src_gen
+ cp /home/plc/OpenPLC_v3/etc/core/server.cpp /home/plc/OpenPLC_v3/build/src_gen
+ cp /home/plc/OpenPLC_v3/etc/core/interactive_server.cpp /home/plc/OpenPLC_v3/build/src_gen
+ cd /home/plc/OpenPLC_v3/build/src_gen
+ '[' linux = win ']'
+ '[' linux = linux ']'
+ echo 'Compiling for Linux'
Compiling for Linux
+ echo 'Generating object files...'
Generating object files...
+ g++ -std=gnu++11 -I /home/plc/OpenPLC_v3/etc/core/lib -c Config0.c -lasiodnp3 -lasiopal -lopendnp3 -lopenpal -w
+ '[' 0 -ne 0 ']'
+ g++ -std=gnu++11 -I /home/plc/OpenPLC_v3/etc/core/lib -c Res0.c -lasiodnp3 -lasiopal -lopendnp3 -lopenpal -w
+ '[' 0 -ne 0 ']'
+ echo 'Generating glueVars...'
Generating glueVars...
+ /home/plc/OpenPLC_v3/build/glue_generator
+ echo 'Compiling main program...'
Compiling main program...
++ pkg-config --cflags --libs libmodbus
+ g++ -std=gnu++11 dnp3.cpp glueVars.cpp hardware_layer.cpp interactive_server.cpp modbus.cpp modbus_master.cpp server.cpp Config0.o Res0.o -o /home/plc/OpenPLC_v3/build/openplc -I /home/plc/OpenPLC_v3/etc/core/lib -pthread -fpermissive -I/usr/local/include/modbus -L/usr/local/lib -lmodbus -lasiodnp3 -lasiopal -lopendnp3 -lopenpal -w
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
/tmp/ccLvFpjh.o: In function `asiodnp3::ConsoleLogger::Log(openpal::LogEntry const&)':
dnp3.cpp:(.text+0x1445): undefined reference to `log(unsigned char*)'
/tmp/ccLvFpjh.o: In function `dnp3StartServer(int)':
dnp3.cpp:(.text+0x178e): undefined reference to `bufferLock'
dnp3.cpp:(.text+0x17d1): undefined reference to `bufferLock'
dnp3.cpp:(.text+0x17ea): undefined reference to `sleep_until(timespec*, int)'
/tmp/ccLvFpjh.o: In function `CommandCallback::Operate(opendnp3::ControlRelayOutputBlock const&, unsigned short, opendnp3::OperateType)':
dnp3.cpp:(.text._ZN15CommandCallback7OperateERKN8opendnp323ControlRelayOutputBlockEtNS0_11OperateTypeE[_ZN15CommandCallback7OperateERKN8opendnp323ControlRelayOutputBlockEtNS0_11OperateTypeE]+0x4e): undefined reference to `bufferLock'
dnp3.cpp:(.text._ZN15CommandCallback7OperateERKN8opendnp323ControlRelayOutputBlockEtNS0_11OperateTypeE[_ZN15CommandCallback7OperateERKN8opendnp323ControlRelayOutputBlockEtNS0_11OperateTypeE]+0xc7): undefined reference to `bufferLock'
/tmp/ccLvFpjh.o: In function `CommandCallback::Operate(opendnp3::AnalogOutputInt16 const&, unsigned short, opendnp3::OperateType)':
dnp3.cpp:(.text._ZN15CommandCallback7OperateERKN8opendnp317AnalogOutputInt16EtNS0_11OperateTypeE[_ZN15CommandCallback7OperateERKN8opendnp317AnalogOutputInt16EtNS0_11OperateTypeE]+0x31): undefined reference to `bufferLock'
dnp3.cpp:(.text._ZN15CommandCallback7OperateERKN8opendnp317AnalogOutputInt16EtNS0_11OperateTypeE[_ZN15CommandCallback7OperateERKN8opendnp317AnalogOutputInt16EtNS0_11OperateTypeE]+0xe6): undefined reference to `bufferLock'
/tmp/ccLvFpjh.o: In function `CommandCallback::Operate(opendnp3::AnalogOutputInt32 const&, unsigned short, opendnp3::OperateType)':
dnp3.cpp:(.text._ZN15CommandCallback7OperateERKN8opendnp317AnalogOutputInt32EtNS0_11OperateTypeE[_ZN15CommandCallback7OperateERKN8opendnp317AnalogOutputInt32EtNS0_11OperateTypeE]+0x3c): undefined reference to `bufferLock'
/tmp/ccLvFpjh.o:dnp3.cpp:(.text._ZN15CommandCallback7OperateERKN8opendnp317AnalogOutputInt32EtNS0_11OperateTypeE[_ZN15CommandCallback7OperateERKN8opendnp317AnalogOutputInt32EtNS0_11OperateTypeE]+0x8e): more undefined references to `bufferLock' follow
/tmp/ccTHa3KR.o: In function `createSocket_interactive(int)':
interactive_server.cpp:(.text+0x1e3): undefined reference to `log(unsigned char*)'
interactive_server.cpp:(.text+0x2e7): undefined reference to `log(unsigned char*)'
interactive_server.cpp:(.text+0x333): undefined reference to `log(unsigned char*)'
/tmp/ccTHa3KR.o: In function `waitForClient_interactive(int)':
interactive_server.cpp:(.text+0x383): undefined reference to `run_openplc'
interactive_server.cpp:(.text+0x3c0): undefined reference to `sleepms(int)'
/tmp/ccTHa3KR.o: In function `processCommand(unsigned char*, int)':
interactive_server.cpp:(.text+0x523): undefined reference to `log(unsigned char*)'
interactive_server.cpp:(.text+0x592): undefined reference to `log(unsigned char*)'
interactive_server.cpp:(.text+0x5fb): undefined reference to `log(unsigned char*)'
interactive_server.cpp:(.text+0x601): undefined reference to `run_openplc'
interactive_server.cpp:(.text+0x673): undefined reference to `log(unsigned char*)'
interactive_server.cpp:(.text+0x6c7): undefined reference to `log(unsigned char*)'
interactive_server.cpp:(.text+0x72b): undefined reference to `log(unsigned char*)'
interactive_server.cpp:(.text+0x7d1): undefined reference to `log(unsigned char*)'
interactive_server.cpp:(.text+0x840): undefined reference to `log(unsigned char*)'
/tmp/ccTHa3KR.o:interactive_server.cpp:(.text+0x8b1): more undefined references to `log(unsigned char*)' follow
/tmp/ccTHa3KR.o: In function `processCommand(unsigned char*, int)':
interactive_server.cpp:(.text+0xab0): undefined reference to `log_index'
interactive_server.cpp:(.text+0xac0): undefined reference to `log_buffer'
/tmp/ccTHa3KR.o: In function `handleConnections_interactive(void*)':
interactive_server.cpp:(.text+0xd7d): undefined reference to `run_openplc'
/tmp/ccTHa3KR.o: In function `startInteractiveServer(int)':
interactive_server.cpp:(.text+0xe7b): undefined reference to `run_openplc'
interactive_server.cpp:(.text+0xf05): undefined reference to `log(unsigned char*)'
interactive_server.cpp:(.text+0x100b): undefined reference to `log(unsigned char*)'
/tmp/ccYc4zCJ.o: In function `mapUnusedIO()':
modbus.cpp:(.text+0x30): undefined reference to `bufferLock'
modbus.cpp:(.text+0x2ca): undefined reference to `bufferLock'
/tmp/ccYc4zCJ.o: In function `ReadCoils(unsigned char*, int)':
modbus.cpp:(.text+0x421): undefined reference to `bufferLock'
modbus.cpp:(.text+0x5d2): undefined reference to `bufferLock'
/tmp/ccYc4zCJ.o: In function `ReadDiscreteInputs(unsigned char*, int)':
modbus.cpp:(.text+0x6fa): undefined reference to `bufferLock'
/tmp/ccYc4zCJ.o:modbus.cpp:(.text+0x8ab): more undefined references to `bufferLock' follow
/tmp/ccJWr7jC.o: In function `parseConfig()':
modbus_master.cpp:(.text+0xd9d): undefined reference to `log(unsigned char*)'
/tmp/ccJWr7jC.o: In function `querySlaveDevices(void*)':
modbus_master.cpp:(.text+0x11ad): undefined reference to `run_openplc'
modbus_master.cpp:(.text+0x1267): undefined reference to `log(unsigned char*)'
modbus_master.cpp:(.text+0x12ed): undefined reference to `log(unsigned char*)'
modbus_master.cpp:(.text+0x140b): undefined reference to `log(unsigned char*)'
modbus_master.cpp:(.text+0x1626): undefined reference to `log(unsigned char*)'
modbus_master.cpp:(.text+0x191f): undefined reference to `log(unsigned char*)'
/tmp/ccJWr7jC.o:modbus_master.cpp:(.text+0x1aee): more undefined references to `log(unsigned char*)' follow
/tmp/ccJWr7jC.o: In function `querySlaveDevices(void*)':
modbus_master.cpp:(.text+0x20cd): undefined reference to `sleepms(int)'
/tmp/cctZcObv.o: In function `createSocket(int)':
server.cpp:(.text+0x1f7): undefined reference to `log(unsigned char*)'
server.cpp:(.text+0x2f3): undefined reference to `log(unsigned char*)'
server.cpp:(.text+0x33c): undefined reference to `log(unsigned char*)'
/tmp/cctZcObv.o: In function `waitForClient(int)':
server.cpp:(.text+0x3d9): undefined reference to `log(unsigned char*)'
server.cpp:(.text+0x439): undefined reference to `sleepms(int)'
/tmp/cctZcObv.o: In function `handleConnections(void*)':
server.cpp:(.text+0x535): undefined reference to `log(unsigned char*)'
server.cpp:(.text+0x5af): undefined reference to `log(unsigned char*)'
server.cpp:(.text+0x5e7): undefined reference to `log(unsigned char*)'
server.cpp:(.text+0x673): undefined reference to `log(unsigned char*)'
/tmp/cctZcObv.o: In function `startServer(int)':
server.cpp:(.text+0x73b): undefined reference to `log(unsigned char*)'
/tmp/cctZcObv.o:server.cpp:(.text+0x77a): more undefined references to `log(unsigned char*)' follow
collect2: error: ld returned 1 exit status
+ '[' 1 -ne 0 ']'
+ echo 'Error compiling C openplc files'
Error compiling C openplc files
+ echo 'Compilation finished with errors!'
Compilation finished with errors!
+ exit 1
```

**Comment by pedromorgan** [comment]
DOH! fixed above

**Comment by pedromorgan** [comment]
@thiagoralves Can you have a look at this patch as it changes structure+build, but cleans it up a lot.

Its kinda chicken and egg for the new webserver/templating

**Comment by pedromorgan** [comment]
(and before final merge, will make a PR with all changes as one, instead of all noise above)

**Comment by thiagoralves** [comment]
I'll take a look at that and let you know. Thank you for organizing
everything. About your dnp3.cfg file, as far as I know both are identical.
They are in both locations because it must be present in the root directory
where OpenPLC runtime is called. When the webserver calls it, it is in
/webserver. When the user manually calls it, it is usually in
/webserver/core. So, just to be sure, I let the file on both dirs. I know,
this is a lazy dirty hack. The right way would be to have the runtime look
at both places until it finds one. Maybe we could have a dir with all the
.cfg files in it. Modbus master also has a .cfg file generated by the
webserver.

**Comment by pedromorgan** [comment]
The dnpc.cfg files are different, offset_di/do etc..
-  one has `offset_* = 0` 
-  the other has `offset_* = 800`

**Comment by pedromorgan** [comment]
@thiagoralves also check https://openplcproject.gitlab.io/getting-started/

**Comment by thiagoralves** [comment]
dang it... the right one should be offset... = 0. Probably it is something
that someone uploaded on a git push and I didn't notice.

**Comment by thiagoralves** [comment]
That's really good! The website looks nice and a lot more lightweight than
Wix bloated stuff. There are two things I always wanted to add on the
OpenPLC website. One is a wiki with information about OpenPLC internals
(code files, functions, variables, etc). The other is a user collaborative
space that allows people to upload their custom hardware drivers and custom
PLC Function Blocks. Something like the Arduino playground:
https://playground.arduino.cc/

**Comment by pedromorgan** [comment]
That's using jekyll and a static site generator.

we could probbly crate a gitlab project for wiki only..
but should internals not be documented in the code, and then use doxygen ??

**Comment by thiagoralves** [comment]
The wiki could have doxygen documentation as well. But I was thinking to
also add some basic documentation to it.

**Pull request closed without merging**
